using System.Collections.Generic;

namespace ZeroPlus.Oms.Config
{
    public class TbRouteMapping
    {
        public HashSet<string> TbRoutes { get; set; }
        public Dictionary<string, string> RouteMappings { get; set; }
        public string DefaultRoute { get; set; }
        public static TbRouteMapping Default { get; internal set; } = new TbRouteMapping()
        {
            TbRoutes = new HashSet<string>()
            {
                "TAMEX",
                "TARCA",
                "TBATS",
                "TC2",
                "TCBOE",
                "TEDGX",
                "TEMLD",
                "TGEMINI",
                "TISE",
                "TMCRY",
                "TMIAX",
                "TMPRL",
                "TNASDAQ",
                "TNQBX",
                "TPHLX",
                "TAMEX",
                "TARCA",
                "TBATS",
                "TBOX",
                "TC2",
                "TCBOE",
                "TEDGX",
                "TEMLD",
                "TGEMINI",
                "TISE",
                "TMCRY",
                "TMIAX",
                "TMPRL",
                "TNQBX",
                "TPHLX",
                "TEXCH_ROLL",
                "TEXCH_ROLL_S",
                "TEXCH_ROLL_SR",
                "TAMEX",
                "TARCA",
                "TBOX",
                "TC2",
                "TCBOE",
                "TEDGX",
                "TEMLD",
                "TGEMINI",
                "TISE",
                "TMCRY",
                "TMIAX",
                "TMPRL",
                "TNASDAQ",
                "TNQBX",
                "TPHLX",
                "TZPROLL",
                "TZPSROLL",
                "ISMART",
                "INET-ARCA",
                "INET-BOX",
                "INET-C2",
                "INET-CBOE",
                "INET-EDGX",
                "INET-ISE",
                "INET-MCRY",
                "INET-MIAX",
                "INET-NASDAQ",
                "INET-PHLX",
                "INET-AMEX",
                "INET-BATS",
                "INET-BX",
                "INET-GEM",
                "INET-MPRL",
                "INET-ARCA",
                "INET-BOX",
                "INET-C2",
                "INET-CBOE",
                "INET-EDGX",
                "INET-ISE",
                "INET-MCRY",
                "INET-MIAX",
                "INET-NASDAQ",
                "INET-PHLX",
                "INET-AMEX",
                "INET-BATS",
                "INET-BX",
                "INET-GEM",
                "INET-MPRL",
            },
            RouteMappings = new Dictionary<string, string>()
            {
                {"BAMEX", "TAMEX"},
                {"BARCA", "TARCA"},
                {"BBATS", "TBATS"},
                {"BC2", "TC2"},
                {"BCBOE", "TCBOE"},
                {"BEDGX", "TEDGX"},
                {"BEMLD", "TEMLD"},
                {"BGEMINI", "TGEMINI"},
                {"BISE", "TISE"},
                {"BMCRY", "TMCRY"},
                {"BMIAX", "TMIAX"},
                {"BMPRL", "TMPRL"},
                {"BNASDAQ", "TNASDAQ"},
                {"BNQBX", "TNQBX"},
                {"BPHLX", "TPHLX"},
                {"DAMEX", "TAMEX"},
                {"DARCA", "TARCA"},
                {"DBATS", "TBATS"},
                {"DBOX", "TBOX"},

                {"DC2", "TC2"},
                {"DCBOE", "TCBOE"},
                {"DEDGX", "TEDGX"},
                {"DEMLD", "TEMLD"},
                {"DGEMINI", "TGEMINI"},
                {"DISE", "TISE"},
                {"DMERC", "TMCRY"},
                {"DMIAX", "TMIAX"},
                {"DMPRL", "TMPRL"},
                {"DNQBX", "TNQBX"},
                {"DPHLX", "TPHLX"},

                {"EXCH_ROLL", "TEXCH_ROLL"},
                {"EXCH_ROLL_S", "TEXCH_ROLL_S"},
                {"EXCH_ROLL_SR", "TEXCH_ROLL_SR"},

                {"IAMEX", "TAMEX"},
                {"IARCA", "TARCA"},
                {"IBOX", "TBOX"},
                {"IC2", "TC2"},
                {"ICBOE", "TCBOE"},
                {"IEDGX", "TEDGX"},
                {"IEMLD", "TEMLD"},
                {"IGEMNI", "TGEMINI"},
                {"IISE", "TISE"},
                {"IMCRY", "TMCRY"},
                {"IMIAX", "TMIAX"},
                {"IMPRL", "TMPRL"},
                {"INASDAQ", "TNASDAQ"},
                {"INQBX", "TNQBX"},
                {"IPHLX", "TPHLX"},

                {"ZPROLL", "TZPROLL"},
                {"ZPSROLL", "TZPSROLL"},

                {"TAMEX", "TAMEX"},
                {"TARCA", "TARCA"},
                {"TBATS", "TBATS"},
                {"TBOX", "TBOX"},
                {"TC2", "TC2"},
                {"TCBOE", "TCBOE"},
                {"TEDGX", "TEDGX"},
                {"TEMLD", "TEMLD"},
                {"TGEMINI", "TGEMINI"},
                {"TISE", "TISE"},
                {"TMCRY", "TMCRY"},
                {"TMIAX", "TMIAX"},
                {"TMPRL", "TMPRL"},
                {"TNQBX", "TNQBX"},
                {"TPHLX", "TPHLX"},
                {"TEXCH_ROLL", "TEXCH_ROLL"},
                {"TEXCH_ROLL_S", "TEXCH_ROLL_S"},
                {"TEXCH_ROLL_SR", "TEXCH_ROLL_SR"},
                {"TNASDAQ", "TNASDAQ"},
                {"TZPROLL", "TZPROLL"},
                {"TZPSROLL", "TZPSROLL" },

                {"DSENSOR", "ISMART" },
                {"ISMART", "ISMART" },

                {"INET-SMART","ISMART"},
                {"INET-ARCA","INET-ARCA"},
                {"INET-BOX","INET-BOX"},
                {"INET-C2","INET-C2"},
                {"INET-CBOE","INET-CBOE"},
                {"INET-EDGX","INET-EDGX"},
                {"INET-ISE","INET-ISE"},
                {"INET-MCRY","INET-MCRY"},
                {"INET-MIAX","INET-MIAX"},
                {"INET-NASDAQ","INET-NASDAQ"},
                {"INET-PHLX","INET-PHLX"},
                {"INET-AMEX","INET-AMEX"},
                {"INET-BATS","INET-BATS"},
                {"INET-BX","INET-BX"},
                {"INET-GEM","INET-GEM"},
                {"INET-MPRL","INET-MPRL" },
            },
            DefaultRoute = "TEXCH_ROLL",
        };
    }
}
