using Org.SbeTool.Sbe.Dll;
using System;
using System.Collections.Generic;
using System.Xml;
using ZeroPlus.Models.Data.Auth;
using ZeroPlus.Models.Data.Edge;
using ZeroPlus.Models.Data.EdgeScanner;
using ZeroPlus.Models.Data.Enums;
using ZeroPlus.Models.Data.Matrix.Strategies;
using ZeroPlus.Models.Data.Models;
using ZeroPlus.Models.Data.Models.Databento;
using ZeroPlus.Models.Data.Portfolio.Interfaces;
using ZeroPlus.Models.Data.Requests;
using ZeroPlus.Models.Data.Responses;
using ZeroPlus.Models.Data.Securities;
using ZeroPlus.Models.Data.SpiderRock;
using ZeroPlus.Models.Data.Subscription;
using ZeroPlus.Models.Data.Subscription.Topics;
using ZeroPlus.Models.Data.Trading;
using ZeroPlus.Models.Data.Trading.Interfaces;
using ZeroPlus.Models.Data.Update;
using ZeroPlus.Models.Data.Update.Interfaces;
using ZeroPlus.Models.Generators.SpreadGenerators;

namespace ZeroPlus.Models.Protocols.Sbe.Interfaces
{
    public interface ISbeMessageEncoder
    {
        // All Encode methods write into the caller-provided DirectBuffer at the given offset
        // and return the total number of bytes written (including the MessageHeader).
        int EncodeClientAuthentication(DirectBuffer directBuffer, int offset, ref ClientAuthenticationModel model);
        int EncodeClientRegistration(DirectBuffer directBuffer, int offset, ref ClientRegistrationModel model);
        int EncodeLatencyMeterEvent(DirectBuffer directBuffer, int offset, ref LatencyMeterEventModel model);
        int EncodeStateSnapshot(DirectBuffer directBuffer, int offset, ref StateSnapshotModel model);
        int EncodeSubscribeMarketDataRequest(DirectBuffer directBuffer, int offset, ref SubscribeMarketDataModel model);
        int EncodeSubscribePnlRequest(DirectBuffer directBuffer, int offset, ref SubscribePnlModel subscribePnl);
        int EncodeSubscribeTransactionRequest(DirectBuffer directBuffer, int offset, ref SubscribeTransactionModel model);
        int EncodeUnsubscribeMarketDataRequest(DirectBuffer directBuffer, int offset, ref UnsubscribeMarketDataModel model);
        int EncodeUnsubscribePnlRequest(DirectBuffer directBuffer, int offset, ref UnsubscribePnlModel unsubscribePnl);
        int EncodeUnsubscribeTransactionRequest(DirectBuffer directBuffer, int offset, ref UnsubscribeTransactionModel model);
        int EncodeMultipleOrderAdded(DirectBuffer directBuffer, int offset, int requestId, IOrder[] orders, int count, int totalQueued, int lastMessageIndex);
        int EncodeOrderAdded(DirectBuffer directBuffer, int offset, IOrder order);
        int EncodeOrderRemoved(DirectBuffer directBuffer, int offset, string permId);
        int EncodeOrderUpdate(DirectBuffer directBuffer, int offset, IOrder order);
        int EncodeOrderIndicatorUpdate(DirectBuffer directBuffer, int offset, IOrder order);
        int EncodeOrderTagUpdate(DirectBuffer directBuffer, int offset, IOrder order);
        int EncodePortfolioAdded(DirectBuffer directBuffer, int offset, IPortfolio portfolio);
        int EncodePositionAdded(DirectBuffer directBuffer, int offset, IPortfolio portfolio, IPosition position);
        int EncodePositionUpdated(DirectBuffer directBuffer, int offset, IPortfolio portfolio, IPosition[] positions, bool isReplay);
        int EncodePositionUpdatedSlim(DirectBuffer directBuffer, int offset, IPortfolio portfolio, IPosition[] positions, bool isReplay);
        int EncodeSecurityDoubleDecimalUpdate(DirectBuffer directBuffer, int offset, int id, SubscriptionFieldType type, double bidUpdate, double askUpdate, DateTime lastUpdateTime, double bidChange, double askChange, int bidSize, int askSize, double lastPrice, double latencyMs = 0);
        int EncodeDeltaAdjTheoUpdate(DirectBuffer directBuffer, int offset, ref AdjTheoUpdate theoUpdate);
        int EncodeMultiplePortfoliosAddedMessage(DirectBuffer directBuffer, int offset, int requestId, ICollection<IPortfolio> portfolios);
        int EncodeRequestPnlFromArchiveMessage(DirectBuffer directBuffer, int offset, int requestId, DateTime startDateTime, DateTime endDateTime, bool requestPreCalcs, bool includeBreakdownStats, List<string> apiUsernames, List<string> tags, List<string> symbols, List<string> underlyings);
        int EncodeRequestTransactionsFromArchiveMessage(DirectBuffer directBuffer, int offset, int requestId, DateTime startDateTime, DateTime endDateTime, bool ordersOnly, List<OrderStatus> orderStatus, List<string> apiUsernames, List<string> tags, List<string> symbols, List<string> underlyings);
        int EncodeRequestAuditTrailMessage(DirectBuffer directBuffer, int offset, int requestId, string orderId);
        int EncodeRequestOrderDetailsMessage(DirectBuffer directBuffer, int offset, int requestId, string orderId);
        int EncodeAuditTrailResponseMessage(DirectBuffer directBuffer, int offset, int requestId, string orderId, XmlDocument xmlDocument);
        int EncodeHanweckUpdatesWithMatchingTimestampsRequestMessage(DirectBuffer directBuffer, int offset, int requestId, List<string> symbols);
        int EncodeHanweckUpdatesWithMatchingTimestampsResponseMessage(DirectBuffer directBuffer, int offset, int requestId, bool updateFound, DateTime timestamp, double price, Dictionary<string, double> symbolToTheoMap);
        int EncodeSymbolMapRequestMessage(DirectBuffer directBuffer, int offset, int requestId);
        int EncodeSymbolMapResponseMessage(DirectBuffer directBuffer, int offset, int requestId, Dictionary<string, int> symbolToIndexMap, bool lastGroup);
        int EncodeRootSymbolMapRequestMessage(DirectBuffer directBuffer, int offset, int requestId);
        int EncodeRootSymbolMapResponseMessage(DirectBuffer directBuffer, int offset, int requestId, Dictionary<Security, int> symbolToIndexMap, bool lastGroup);
        int EncodeMultipleSecurityDecimalUpdateMessage(DirectBuffer directBuffer, int offset, SubscriptionFieldType subscriptionFieldType, Dictionary<int, (double update, double bidUpdate, double askUpdate)> symbolIdToUpdateMap);
        int EncodeDoubleUpdate(DirectBuffer directBuffer, int offset, int id, SubscriptionFieldType fieldType, uint updateSequence, ulong underlyingTimestamp, ulong snapshotTimestamp, ulong hanweckTimestamp, double theo, double delta, double gamma, double vega, double theta, double rho, double implied, double latestMidPrice, double snapshotMidPrice, double deltaAdjustedTheo, bool jumpDetected);
        int EncodeOptionSnapshotRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol, DateTime expiration, double delta, DateTime startDateTime, DateTime endDateTime);
        int EncodeOptionSnapshotResponseMessage(DirectBuffer directBuffer, int offset, int requestId, bool found, List<OptionSnapshot> snapshots);
        int EncodeMarketCrossScanRequestMessage(DirectBuffer directBuffer, int offset, int requestId, double lookbackInSeconds, double minMarketCross, double currentMarketWidth);
        int EncodeMarketCrossScanResponseMessage(DirectBuffer directBuffer, int offset, int requestId, bool found, List<MarketCrossScanResult> snapshots);
        int EncodeBestEdgeToTheoRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string underlying, BaseStrategy baseStrategy, int expirationIds);
        int EncodeBestEdgeToTheoResponseMessage(DirectBuffer directBuffer, int offset, int requestId, double bestBuyEdgeToTheo, double avgBuyEdgeToTheo, double lastBuyEdgeToTheo, DateTime lastBuyEdgeToTheoTime, double bestSellEdgeToTheo, double avgSellEdgeToTheo, double lastSellEdgeToTheo, DateTime lastSellEdgeToTheoTime);
        int EncodeOptionSymbolMapResponseMessage(DirectBuffer directBuffer, int offset, int requestId, Dictionary<Option, int> symbolToIndexMap, bool lastGroup);
        int EncodeSymbolTradeRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol);
        int EncodeSymbolTradeResponseMessage(DirectBuffer directBuffer, int offset, int requestId, Generated.FishStatus fishStatus, double fishLevel, double fishEdge, double fishLevelSell, double fishEdgeSell, DateTime lastfishTime);
        int EncodeSymbolsTradeRequestMessage(DirectBuffer directBuffer, int offset, int requestId, bool includeOutrights, bool includeSpreads, bool includeBackdays, DateTime lastDateToInclude, string underlyings, string symbols, string tags);
        int EncodeSymbolTradesResponseMessage(DirectBuffer directBuffer, int offset, int requestId, List<SymbolFishStatusResponse> responses, bool lastMessage);
        int EncodeEdgeScanFeedModel(DirectBuffer directBuffer, int offset, IEdgeScanFeedModel updatedOrder, string? sessionId = null, string? message = null, string? reason = null);
        int EncodeTradeFeedModel(DirectBuffer directBuffer, int offset, int id, List<ITradeFeedModel> models, bool isLast);
        int EncodeTimeUpdateMessage(DirectBuffer directBuffer, int offset, TimeFeedType timeFeedType, DateTime timestamp);
        int EncodeTradeUpdate(DirectBuffer directBuffer, int offset, ref TradeUpdateModel lastTrade);
        int EncodeSecurityEmaUpdate(DirectBuffer directBuffer, int offset, int securityId, SubscriptionFieldType type, EmaUpdateModel emaUpdateModel);
        int EncodeSingleOrderRequestMessage(DirectBuffer directBuffer, int offset, SingleOrderRequest singleOrderRequest);
        int EncodePairOrderRequestMessage(DirectBuffer directBuffer, int offset, PairOrderRequest singleOrderRequest);
        int EncodeAccountRequestMessage(DirectBuffer directBuffer, int offset, int requestId);
        int EncodeAccountResponseMessage(DirectBuffer directBuffer, int offset, int requestId, List<Account> accounts);
        int EncodeOrderInfoUpdate(DirectBuffer directBuffer, int offset, OrderInfoUpdate orderInfo);
        int EncodeBasketOrderRequestMessage(DirectBuffer directBuffer, int offset, BasketOrderRequest basketOrderRequest);
        int EncodeResetBaseLineRequestMessage(DirectBuffer directBuffer, int offset, List<string> symbols);
        int EncodeDerivedValueUpdate(DirectBuffer directBuffer, int offset, DerivedValueUpdateModelContainer model);
        int EncodeTheoToMarketSpreadUpdate(DirectBuffer directBuffer, int offset, TheoToMarketSpread model);
        int EncodeIbQuoteUpdate(DirectBuffer directBuffer, int offset, IbQuoteUpdateModel updateModel);
        int EncodeEdgeToTheoUpdate(DirectBuffer directBuffer, int offset, EdgeToTheoUpdateModel updateModel);
        int EncodeOrderDetailsResponseMessage(DirectBuffer directBuffer, int offset, int requestId, string orderId, string json);
        int EncodeAutoTraderConfigMessage(DirectBuffer directBuffer, int offset, int requestId, string json);
        int EncodeSendOrder(DirectBuffer directBuffer, int offset, IOrderSlim order);
        int EncodeOrderUpdateValuesMessage(DirectBuffer directBuffer, int offset, OrderUpdateValues orderUpdate);
        int EncodeSymbolStatModelAddedMessage(DirectBuffer directBuffer, int offset, ISymbolStatModel model);
        int EncodeSymbolStatModelUpdateMessage(DirectBuffer directBuffer, int offset, ISymbolStatModel model);
        int EncodeSpreadRiskModel(DirectBuffer directBuffer, int offset, ISpreadRiskModel update);
        int EncodeSelfTradeWarningModel(DirectBuffer directBuffer, int offset, ISelfTradeModel model);
        int EncodeCancelOrderRequestMessage(DirectBuffer directBuffer, int offset, CancelRequest cancelRequest);
        int EncodeTagOrderMessage(DirectBuffer directBuffer, int offset, string permId, bool isTagged, string tagger, string taggedMessage);
        int EncodeSymbolEdgeMapRequest(DirectBuffer directBuffer, int offset, int requestId, string symbol, DateTime start);
        int EncodeSymbolEdgeMapResponse(DirectBuffer directBuffer, int offset, int requestId, string symbol, DateTime start, IEnumerable<SymbolEdgeMap> symbolEdgeMaps);
        int EncodeBarRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol, DateTime rangeStart, DateTime rangeEnd);
        int EncodeBarResponseMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol, List<BarModel> bars, bool lastGroup);
        int EncodeAlertMessage(DirectBuffer directBuffer, int offset, AlertMessageModel alertMessage);
        int EncodeGreekUpdate(DirectBuffer directBuffer, int offset, GreekUpdateModel updateModel);
        int EncodeModifyOrderRequestMessage(DirectBuffer directBuffer, int offset, ModifyRequest modifyRequest);
        int EncodeSymbolStrikeRangeRequest(DirectBuffer directBuffer, int offset, int reqId, string symbol, double delta, DateTime expiration);
        int EncodeSymbolStrikeRangeResponse(DirectBuffer directBuffer, int offset, int reqId, double strikeRange);
        int EncodePermEdgeToTheoMappingMessage(DirectBuffer directBuffer, int offset, string symbol, List<EdgeToTheoTrackerModel> mappings);
        int EncodeRegisterEdgeScanFeedServerRunnerJson(DirectBuffer directBuffer, int offset, string json);
        int EncodeUnregisterEdgeScanFeedServerRunner(DirectBuffer directBuffer, int offset, string id);
        int EncodeSpreadGeneratorRequestMessage(DirectBuffer directBuffer, int offset, int requestId, SpreadsGeneratorConfig config);
        int EncodeSpreadGeneratorResultsMessage(DirectBuffer directBuffer, int offset, int requestId, Span<Spread> results, bool lastGroup);
        int EncodeSymbolsRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol, string secType, string exchange, string currency);
        int EncodeSymbolsResponseMessage(DirectBuffer directBuffer, int offset, int requestId, List<Option> results, bool lastGroup);
        int EncodeOptionChainRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string underlying, int? expiryFromYyMMdd, int? expiryToYyMMdd, double? strikeMin, double? strikeMax, PutCall? putCallFilter);
        int EncodeOptionChainResponseMessage(DirectBuffer directBuffer, int offset, int requestId, IReadOnlyList<Option> results, bool lastGroup);
        int EncodeEdgeScanFeedStatisticsModel(DirectBuffer directBuffer, int offset, IEdgeScanFeedStatisticsSummary model);
        int EncodeEdgeScanFeedStatisticsMiniUpdate(DirectBuffer directBuffer, int offset, IEdgeScanFeedStatisticsSummary model);
        int EncodeChartSeriesUpdateMessage(DirectBuffer directBuffer, int offset, string id, SubscriptionFieldType type, IReadOnlyList<ChartValueModel> updates, int startIndex);
        int EncodeFirmOrderAndTradeSummary(DirectBuffer directBuffer, int offset, FirmOrderAndTradeSummary summary);
        int EncodeDataRequestMessage(DirectBuffer directBuffer, int offset, int requestId, SubscriptionFieldType type);
        int EncodeHistoricHighestBidLowestAskRequestMessage(DirectBuffer directBuffer, int offset, int requestId, int tickerId, string symbol);
        int EncodeHistoricHighestBidLowestAskResponseMessage(DirectBuffer directBuffer, int offset, int requestId, int tickerId, string symbol, List<HighestBidLowestAskTrackerModel> updates);
        int EncodePositionsRequest(DirectBuffer directBuffer, int offset, int requestId, string portfolioName, PortfolioType portfolioType, PositionType positionType);
        int EncodeMultiplePositionsAdded(DirectBuffer directBuffer, int offset, int requestId, IPortfolio portfolio, IPosition[] chunk);
        int EncodePriceChainModel(DirectBuffer directBuffer, int offset, IPriceChainModel model, string? sessionId = null);
        int EncodeMatrixSyntheticSpreadMessage(DirectBuffer directBuffer, int offset, SyntheticSpread model);
        int EncodeMatrixScrapeMessage(DirectBuffer directBuffer, int offset, Scrape model);
        int EncodeMatrixSeekerMessage(DirectBuffer directBuffer, int offset, Seeker model);
        int EncodeMatrixSeekerSpreadMessage(DirectBuffer directBuffer, int offset, SeekerSpread model);
        int EncodeTransactionMessage(DirectBuffer directBuffer, int offset, Transaction updatedOrder);
        int EncodeOrderTagMessage(DirectBuffer directBuffer, int offset, OrderTagModel orderTagModel);
        int EncodeModifySmartOrderRequestMessage(DirectBuffer directBuffer, int offset, ModifySmartRequest ModifySmartRequest);
        int EncodeModeledTheoUpdateMessage(DirectBuffer directBuffer, int offset, ModeledTheoUpdate model);
        int EncodeSpreadBookQuoteMessage(DirectBuffer directBuffer, int offset, SpreadBookQuote model);
        int EncodeCobTradeRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string underlying, DateTime startTime, DateTime endTime, int limit);
        int EncodeCancelDataRequestMessage(DirectBuffer directBuffer, int offset, int requestId, SubscriptionFieldType fieldType);
        int EncodeCobTradeResponseMessage(DirectBuffer directBuffer, int offset, int requestId, List<SpreadExchPrint> prints);
        int EncodeSpreadExchOrderMessage(DirectBuffer directBuffer, int offset, SpreadExchOrder model);
        int EncodeSpreadPrintMessage(DirectBuffer directBuffer, int offset, SpreadPrint model);
        int EncodeAuctionPrintMessage(DirectBuffer directBuffer, int offset, AuctionPrint model);
        int EncodeModelDescriptionMessage(DirectBuffer directBuffer, int offset, byte modelId, string description);
        int EncodeSlimGreekUpdateMessage(DirectBuffer directBuffer, int offset, SlimGreekUpdateModel update);
        int EncodeCancelTokenMessage(DirectBuffer directBuffer, int offset, int requestId, string token);
        int EncodeImpliedQuoteUpdateMessage(DirectBuffer directBuffer, int offset, ImpliedQuoteUpdate update);
        int EncodeGetClosestOptionRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string underlying, SubscriptionFieldType field, PutCall putCall, DateTime expiration, double value);
        int EncodeGetClosestOptionResponseMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol);
        int EncodeNextOptionPermsRequestMessage(DirectBuffer directBuffer, int offset, int requestId, string symbol, PermutationDirection direction, PermMode mode, int count);
        int EncodeNextOptionPermsResponseMessage(DirectBuffer directBuffer, int offset, int requestId, IReadOnlyList<string> symbols, bool lastGroup);
        int EncodeNextSpreadPermsRequestMessage(DirectBuffer directBuffer, int offset, int requestId, IReadOnlyList<PermLegRequest> legs, PermutationDirection direction, PermMode mode, PermSide permSide, int count, BaseStrategy baseStrategy, bool maintainBaseStrategy, bool maintainBaseStrategyFlyException, bool skipCheck);
        int EncodeNextSpreadPermsResponseMessage(DirectBuffer directBuffer, int offset, int requestId, IReadOnlyList<PermSpreadResult> perms, bool lastGroup);
        int EncodeJsonRequestMessage(DirectBuffer directBuffer, int offset, JsonRequest jsonRequest);
        int EncodeJsonResponseMessage(DirectBuffer directBuffer, int offset, JsonResponse jsonResponse);
        int EncodeRiskCheckResultMessage(DirectBuffer directBuffer, int offset, IHaveRisk jsonResponse);
        int EncodeOrderRiskRequestMessage(DirectBuffer directBuffer, int offset, OrderRisk riskRequest);
        int EncodeCancelRiskRequestMessage(DirectBuffer directBuffer, int offset, CancelRisk riskRequest);
        int EncodeCancelReplaceRiskRequestMessage(DirectBuffer directBuffer, int offset, CancelReplaceRisk riskRequest);
        int EncodeOrderUpdateModelMessage(DirectBuffer directBuffer, int offset, OrderUpdateModel orderUpdateModel);
        int EncodeFitUpdateMessage(DirectBuffer directBuffer, int offset, UnderFitResult underFitResult);
        int EncodeAutomationStateChangeMessage(DirectBuffer directBuffer, int offset, string id, bool automationRunning);
        int EncodeSubmissionSummaryUpdateMessage(DirectBuffer directBuffer, int offset, SubmissionsSummary uniqueSubmissionsSummary);
        int EncodePerformanceModeRequestMessage(DirectBuffer directBuffer, int offset, bool isPerformanceModeEnabled);
        int EncodePricingRequestMessage(DirectBuffer directBuffer, int offset, PricingRequestModel request);
        int EncodePricingResponseMessage(DirectBuffer directBuffer, int offset, PricingResponseModel response);
        int EncodeTradeRequestMessage(DirectBuffer directBuffer, int offset, uint requestId, string symbol, DateTime start, DateTime end);
        int EncodeTradeResponseMessage(DirectBuffer directBuffer, int offset, uint requestId, bool lastMessage, uint count, List<MbpTradeModel> trades);
        int EncodeAddRemoveMultipleTradesMessage(DirectBuffer directBuffer, int offset, bool add, List<string> permIds);
        int EncodeMultipleContrapartyReportsAddedMessage(DirectBuffer directBuffer, int offset, DateTime targetDate, ContraPartyReportModel[] reports, int count);
        int EncodeAutoTraderConfigBinaryMessage(DirectBuffer directBuffer, int offset, AutoTraderConfig config);
        int EncodeTheoBatchUpdateMessage(DirectBuffer directBuffer, int offset, TheoBatchUpdate batchUpdate, long timestamp);
        int EncodeAdjTheoBatchUpdateMessage(DirectBuffer directBuffer, int offset, TheoBatchUpdate batchUpdate, long timestamp);
        int EncodeOpenSpreadExchOrderMessage(DirectBuffer directBuffer, int offset, IOpenSpreadExchOrder update);
        int EncodeRemoveSpreadExchOrderMessage(DirectBuffer directBuffer, int offset, IOpenSpreadExchOrder update);
        int EncodeVolSurfaceRequest(DirectBuffer directBuffer, int offset, VolSurfaceRequestModel model);
        int EncodeVolSurfaceResponse(DirectBuffer directBuffer, int offset, VolSurfaceResponseModel model);
        int EncodeHerculesEchoMessage(DirectBuffer directBuffer, int offset, IOrder order, string? source, Venue venue, int updateType);
        int EncodeHerculesEchoRequestMessage(DirectBuffer directBuffer, int offset, bool requestEcho);
        int EncodeZpTheoUpdateMessage(DirectBuffer directBuffer, int offset, int tickerId, ulong sequence, double theoBid, double theoAsk);
        int EncodeLiveVolDataRequestMessage(DirectBuffer directBuffer, int offset, int requestId, bool getLatest, string? symbol, DateTime startTime, DateTime endTime);
        int EncodeLiveVolDataResponseMessage(DirectBuffer directBuffer, int offset, int requestId, List<LiveVolDataModel> data);
        int EncodeRbboUpdate(DirectBuffer directBuffer, int offset, RbboUpdateModel updateModel);
        int EncodeSymbolIndexMapping(DirectBuffer directBuffer, int offset, int tickerId, string symbol, SubscriptionFieldType subscriptionType);
        int EncodeRegisterForeignUpdateRoute(DirectBuffer directBuffer, int offset, RegisterForeignUpdateRouteRequest model);
        int EncodeUnregisterForeignUpdateRoute(DirectBuffer directBuffer, int offset, UnregisterForeignUpdateRouteRequest model);
        int EncodeReplaceForeignUpdateRoutes(DirectBuffer directBuffer, int offset, ReplaceForeignUpdateRoutesRequest model);
        int EncodeListForeignUpdateRoutes(DirectBuffer directBuffer, int offset, ForeignUpdateRoutesResponse model);
        int EncodeMassCancelRequestMessage(DirectBuffer directBuffer, int offset, MassCancelRequest massCancelRequest);
        int EncodeOpraDatabaseTradesRequestMessage(DirectBuffer directBuffer, int offset, OpraDatabaseTradesRequest opraDatabaseTradesRequest);
        int EncodeOpraDatabaseTradesResponseMessage(DirectBuffer directBuffer, int offset, OpraDatabaseTradesResponse opraDatabaseTradesResponse);
        int EncodeEdgeScanFeedRunnerStartMessage(DirectBuffer directBuffer, int offset, EdgeScanFeedRunnerStartRequest edgeScanRunnerStartRequest);
        int EncodeEdgeScanFeedRunnerStopMessage(DirectBuffer directBuffer, int offset, string runnerId);
        int EncodeEdgeScanFeedRunnerUpdateMessage(DirectBuffer directBuffer, int offset, string runnerId, EdgeScanFeedRunnerState state);
        int EncodeTradeSlim(DirectBuffer directBuffer, int offset, TradeSlim model);

        // Auth Server Messages
        int EncodeAuthLoginRequest(DirectBuffer directBuffer, int offset, AuthLoginRequestModel model);
        int EncodeAuthLoginResponse(DirectBuffer directBuffer, int offset, AuthLoginResponseModel model);
        int EncodeAuthUpdatePasswordRequest(DirectBuffer directBuffer, int offset, AuthUpdatePasswordRequestModel model);
        int EncodeAuthUpdatePasswordResponse(DirectBuffer directBuffer, int offset, AuthUpdatePasswordResponseModel model);
        int EncodeAuthGetUsersRequest(DirectBuffer directBuffer, int offset, AuthGetUsersRequestModel model);
        int EncodeAuthGetUsersResponse(DirectBuffer directBuffer, int offset, AuthGetUsersResponseModel model);
        int EncodeAuthGetConfigsRequest(DirectBuffer directBuffer, int offset, AuthGetConfigsRequestModel model);
        int EncodeAuthGetConfigsResponse(DirectBuffer directBuffer, int offset, AuthGetConfigsResponseModel model);
        int EncodeAuthDeleteConfigRequest(DirectBuffer directBuffer, int offset, AuthDeleteConfigRequestModel model);
        int EncodeAuthDeleteConfigResponse(DirectBuffer directBuffer, int offset, AuthDeleteConfigResponseModel model);
        int EncodeAuthConfigSave(DirectBuffer directBuffer, int offset, AuthConfigSaveModel model);
        int EncodeAuthConfigShare(DirectBuffer directBuffer, int offset, AuthConfigShareModel model);
        int EncodeAuthGetDomListInfosRequest(DirectBuffer directBuffer, int offset, AuthGetDomListInfosRequestModel model);
        int EncodeAuthGetDomListInfosResponse(DirectBuffer directBuffer, int offset, AuthGetDomListInfosResponseModel model);
        int EncodeAuthGetCommissionsRequest(DirectBuffer directBuffer, int offset, AuthGetCommissionsRequestModel model);
        int EncodeAuthGetCommissionsResponse(DirectBuffer directBuffer, int offset, AuthGetCommissionsResponseModel model);
        
        int EncodeSingleFieldUpdateMessage(DirectBuffer directBuffer, int offset, int tickerId, SubscriptionFieldType updateType, double value);
    }
}
