namespace ZeroPlus.Oms.Generators;

internal static class BindableAttributeSource
{
    public const string AttributeName = "BindableAttribute";
    public const string FullyQualifiedName = "ZeroPlus.Oms.Ui.BindableAttribute";
    public const string Namespace = "ZeroPlus.Oms.Ui";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace ZeroPlus.Oms.Ui;

        [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
        internal sealed class BindableAttribute : global::System.Attribute
        {
            public object? Default { get; set; }
            public bool Initialize { get; set; }
        }
        """;
}
