using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace ZeroPlus.Oms.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class NotifyPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("NotifyPropertyAttribute.g.cs", NotifyPropertyAttributeSource.Source));

        var properties = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                NotifyPropertyAttributeSource.FullyQualifiedName,
                predicate: static (node, _) => node is PropertyDeclarationSyntax,
                transform: static (ctx, ct) => GetPropertyInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var collected = properties.Collect();

        context.RegisterSourceOutput(collected, static (spc, props) =>
        {
            var groups = props.GroupBy(p => p.ContainingClassKey.MetadataIdentity);
            foreach (var group in groups)
            {
                var key = group.First().ContainingClassKey;
                GenerateSource(spc, new ClassGenInfo(key, group.ToImmutableArray()));
            }
        });
    }

    private static PropertyInfo? GetPropertyInfo(GeneratorAttributeSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IPropertySymbol propertySymbol)
            return null;

        if (propertySymbol.ContainingType is not { } containingType)
            return null;

        var checkEquality = true;
        foreach (var attr in propertySymbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != NotifyPropertyAttributeSource.FullyQualifiedName)
                continue;

            foreach (var namedArg in attr.NamedArguments)
            {
                if (namedArg.Key == "CheckEquality" && namedArg.Value.Value is bool val)
                    checkEquality = val;
            }
        }

        var backingFieldName = ResolveBackingFieldName(propertySymbol.Name, containingType);

        return new PropertyInfo(
            PropertyName: propertySymbol.Name,
            PropertyType: propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            CheckEquality: checkEquality,
            BackingFieldName: backingFieldName,
            ContainingClassKey: ClassKeyFactory.Create(containingType));
    }

    private static string ResolveBackingFieldName(string propertyName, INamedTypeSymbol containingType)
    {
        var camelCase = $"_{char.ToLowerInvariant(propertyName[0])}{propertyName.Substring(1)}";
        var pascalCase = $"_{propertyName}";

        var members = containingType.GetMembers();
        foreach (var member in members)
        {
            if (member is IFieldSymbol field)
            {
                if (field.Name == camelCase || field.Name == pascalCase)
                    return field.Name;
            }
        }

        return camelCase;
    }

    private static void GenerateSource(SourceProductionContext spc, ClassGenInfo classInfo)
    {
        var key = classInfo.Key;
        var props = classInfo.Properties;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8625");
        sb.AppendLine();
        sb.AppendLine("using ZeroPlus.Oms.Ui.Models;");
        sb.AppendLine();

        NestedPartialClassEmitter.AppendNamespace(sb, key.Namespace);
        NestedPartialClassEmitter.AppendClassOpenings(sb, key);

        var mi = NestedPartialClassEmitter.MemberIndent(key);
        var i1 = mi + "    ";
        var i2 = mi + "        ";
        var i3 = mi + "            ";
        var i4 = mi + "                ";

        foreach (var prop in props)
        {
            var fieldName = prop.BackingFieldName;
            var notifierName = $"_{prop.PropertyName}Notifier";

            sb.AppendLine($"{i1}private Notifier {notifierName} = new(nameof({prop.PropertyName}));");
            sb.AppendLine();
            sb.AppendLine($"{i1}public partial {prop.PropertyType} {prop.PropertyName}");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}get => {fieldName};");
            sb.AppendLine($"{i2}set");
            sb.AppendLine($"{i2}{{");

            var coerceName = $"Coerce{prop.PropertyName}";
            var callbackName = $"On{prop.PropertyName}Changed";

            sb.AppendLine($"{i3}{coerceName}(ref value);");

            if (prop.CheckEquality)
            {
                sb.AppendLine($"{i3}if ({fieldName} != value)");
                sb.AppendLine($"{i3}{{");
                sb.AppendLine($"{i4}{fieldName} = value;");
                sb.AppendLine($"{i4}{notifierName}?.Updated();");
                sb.AppendLine($"{i4}{callbackName}(value);");
                sb.AppendLine($"{i3}}}");
            }
            else
            {
                sb.AppendLine($"{i3}{fieldName} = value;");
                sb.AppendLine($"{i3}{notifierName}?.Updated();");
                sb.AppendLine($"{i3}{callbackName}(value);");
            }

            sb.AppendLine($"{i2}}}");
            sb.AppendLine($"{i1}}}");
            sb.AppendLine();
        }

        foreach (var prop in props)
        {
            sb.AppendLine($"{i1}partial void Coerce{prop.PropertyName}(ref {prop.PropertyType} value);");
            sb.AppendLine($"{i1}partial void On{prop.PropertyName}Changed({prop.PropertyType} value);");
        }
        sb.AppendLine();

        sb.AppendLine($"{i1}private Notifier[] GetGeneratedNotifiers() =>");
        sb.AppendLine($"{i1}[");
        for (int i = 0; i < props.Length; i++)
        {
            var notifierName = $"_{props[i].PropertyName}Notifier";
            var comma = i < props.Length - 1 ? "," : "";
            sb.AppendLine($"{i2}{notifierName}{comma}");
        }
        sb.AppendLine($"{i1}];");
        sb.AppendLine();

        sb.AppendLine($"{i1}private void DisposeGeneratedNotifiers()");
        sb.AppendLine($"{i1}{{");
        foreach (var prop in props)
        {
            var notifierName = $"_{prop.PropertyName}Notifier";
            sb.AppendLine($"{i2}{notifierName} = null;");
        }
        sb.AppendLine($"{i1}}}");

        NestedPartialClassEmitter.AppendClassClosings(sb, key);

        var fileStem = ClassKeyFactory.SanitizeForFileName(key.MetadataIdentity);
        spc.AddSource($"{fileStem}.NotifyProperties.g.cs", sb.ToString());
    }
}

internal readonly record struct PropertyInfo(
    string PropertyName,
    string PropertyType,
    bool CheckEquality,
    string BackingFieldName,
    ClassKey ContainingClassKey);

internal readonly record struct ClassGenInfo(
    ClassKey Key,
    ImmutableArray<PropertyInfo> Properties);
