namespace ZeroPlus.Oms.Generators;

internal static class NotifyPropertyAttributeSource
{
    public const string AttributeName = "NotifyPropertyAttribute";
    public const string FullyQualifiedName = "ZeroPlus.Oms.Ui.NotifyPropertyAttribute";
    public const string Namespace = "ZeroPlus.Oms.Ui";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        namespace ZeroPlus.Oms.Ui;

        [global::System.AttributeUsage(global::System.AttributeTargets.Property)]
        internal sealed class NotifyPropertyAttribute : global::System.Attribute
        {
            public bool CheckEquality { get; set; } = true;
        }
        """;
}
